language: objective-c
osx_image: xcode9
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild -workspace Example/EAIntroView.xcworkspace -scheme EAIntroView-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
before_deploy:
  - carthage build --no-skip-current
  - carthage archive EAIntroView
deploy:
  provider: releases
  api_key:
    secure: KVRgXHYFgNRhn55Sg1ubMBdFRSghJoTJZ7vVc/kY69grj5husQnkKGEikMkGWjQAVetjE0KgQ/UzAXkxf9m4y0BJXc0WCOOzVwmSec3lw4wbPl5QoHSyy7Etfz6ji0FSLTAjLWKz7bU35o3KHB+MU12LzaV82Yvc4h8XcpSnRj8=
  file: EAIntroView.framework.zip
  skip_cleanup: true
  on:
    repo: ealeksandrov/EAIntroView
    tags: true
