language: objective-c
osx_image: xcode7.3
before_install:
  - export LANG=en_US.UTF-8
#  - brew update
#  - brew install carthage
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/EARestrictedScrollView.xcworkspace -scheme EARestrictedScrollView-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
before_deploy:
  - carthage build --no-skip-current
  - carthage archive EARestrictedScrollView
deploy:
  provider: releases
  api_key:
    secure: LnOWVVBpgByOSqHV8jTmtEP1M1WFC/79O9YLnnR1DzaiFGseM48ocXGTBKAn1t6CeGYO7NzjbpolWjYOs2T4IOFNLrfMLX7eeXE1nBfXkcrV2iAe8kN8ga9UvqI1MNWu8ryDQGoiQ2KY69eGxubm9CrKeKP/2AFNxichdo8U5jI=
  file: EARestrictedScrollView.framework.zip
  skip_cleanup: true
  on:
    repo: ealeksandrov/EARestrictedScrollView
    tags: true
