# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

gym(
   scheme: "DaihugouBattle",
   export_method: "ad-hoc",
   export_xcargs: "-allowProvisioningUpdates",
   export_options: { compileBitcode: false }
)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "DaihugouBattle.xcworkspace", scheme: "DaihugouBattle")
    upload_to_testflight
  end
end
